apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "session-manager.fullname" . }}-token-refresher
  labels:
    {{- include "session-manager.labels" . | nindent 4 }}
    app.kubernetes.io/component: token-refresher
spec:
  replicas: {{ .Values.tokenRefresher.replicaCount | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "session-manager.name" . }}
      app.kubernetes.io/component: token-refresher
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "session-manager.name" . }}
        app.kubernetes.io/component: token-refresher
        {{- include "session-manager.labels" . | nindent 8 }}
        {{- with .Values.pod.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.pod.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - name: {{ include "session-manager.name" . }}-token-refresher
          image: "{{ template "session-manager.image" (tuple .Values.image.tokenRefresher $.Chart.AppVersion) }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.image.tokenRefresher.command }}
          command: [{{- toYaml . }}]
          {{- end }}
          {{- with .Values.image.tokenRefresher.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: K8S_NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            {{- with .Values.extraEnvs }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.extraEnvsFrom }}
          envFrom:
          {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: {{ include "session-manager.name" . }}-config-volume
              mountPath: /etc/{{ include "session-manager.name" . }}
              readOnly: true
          {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: {{ include "session-manager.name" . }}-config-volume
          projected:
            sources:
              - configMap:
                  name: {{ include "session-manager.name" . }}-token-refresher-config
      {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pod.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

