apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "session-manager.fullname" . }}-token-refresher
  labels:
    {{- include "session-manager.token-refresher.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "session-manager.token-refresher.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.tokenRefresher.pod.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "session-manager.token-refresher.labels" . | nindent 8 }}
        {{- with .Values.tokenRefresher.pod.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.global.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "session-manager.serviceAccountName" . }}
      {{- with .Values.tokenRefresher.pod.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "session-manager.name" . }}-token-refresher
          {{- with .Values.global.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ template "session-manager.image" (tuple .Values.global.image $.Chart.AppVersion) }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          {{- with .Values.global.image.command }}
          command:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          args: [ "token-refresher" ]
          {{- with .Values.tokenRefresher.ports }}
          ports:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env: []
          {{- with .Values.tokenRefresher.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tokenRefresher.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tokenRefresher.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: {{ include "session-manager.name" . }}-config-volume
              mountPath: /etc/session-manager
              readOnly: true
      volumes:
        - name: {{ include "session-manager.name" . }}-config-volume
          projected:
            sources:
              - configMap:
                  name: {{ include "session-manager.name" . }}-config
      {{- with .Values.tokenRefresher.pod.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
