# syntax=docker/dockerfile:1

FROM golang:1.25 AS builder

WORKDIR /app

ENV GOCACHE=/root/.cache/go-build

RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    --mount=type=bind,target=. \
    CGO_ENABLED=0 \
    go build -o /bin/api-pub ./cmd/api-pub

RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    --mount=type=bind,target=. \
    CGO_ENABLED=0 \
    go build -o /bin/api-int ./cmd/api-int

RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    --mount=type=bind,target=. \
    CGO_ENABLED=0 \
    go build -o /bin/migrate ./cmd/migrate

FROM gcr.io/distroless/static-debian12:debug AS runner

COPY --from=builder /bin/api-pub /bin/api-pub
COPY --from=builder /bin/api-int /bin/api-int

# Migrations
COPY --from=builder /bin/migrate /bin/migrate
COPY sql /sql

EXPOSE 8080
ENTRYPOINT ["/bin/api-pub"]
