version: 3

includes:
    shared:
        taskfile: hack/common/Taskfile_service.yaml
        flatten: true
        excludes: [] # put task names in here which are overwritten in this file
        vars:
            CODE_DIRS: "{{.ROOT_DIR}}/cmd/... {{.ROOT_DIR}}/internal/... {{.ROOT_DIR}}/pkg/... {{.ROOT_DIR}}/integration/... {{.ROOT_DIR}}/sql/..."
            COMPONENTS: session-manager
            REPO_URL: https://github.com/openkcm/session-manager
