// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTrust = `-- name: CreateTrust :exec
INSERT INTO trust (
    tenant_id,
    blocked,
    issuer,
    jwks_uri,
    audiences,
    client_id)
VALUES (
    $1,
    $2,
    $3,
    $4,
    COALESCE($5::text[], '{}'::text[]),
    $6)
`

type CreateTrustParams struct {
	TenantID  string      `db:"tenant_id"`
	Blocked   bool        `db:"blocked"`
	Issuer    string      `db:"issuer"`
	JwksUri   string      `db:"jwks_uri"`
	Audiences []string    `db:"audiences"`
	ClientID  pgtype.Text `db:"client_id"`
}

func (q *Queries) CreateTrust(ctx context.Context, arg CreateTrustParams) error {
	_, err := q.db.Exec(ctx, createTrust,
		arg.TenantID,
		arg.Blocked,
		arg.Issuer,
		arg.JwksUri,
		arg.Audiences,
		arg.ClientID,
	)
	return err
}

const deleteTrust = `-- name: DeleteTrust :execrows
DELETE FROM trust
WHERE tenant_id = $1
`

func (q *Queries) DeleteTrust(ctx context.Context, tenantID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTrust, tenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTrust = `-- name: GetTrust :one
SELECT
    issuer,
    blocked,
    jwks_uri,
    audiences,
    client_id
FROM trust
WHERE tenant_id = $1
`

type GetTrustRow struct {
	Issuer    string      `db:"issuer"`
	Blocked   bool        `db:"blocked"`
	JwksUri   string      `db:"jwks_uri"`
	Audiences []string    `db:"audiences"`
	ClientID  pgtype.Text `db:"client_id"`
}

func (q *Queries) GetTrust(ctx context.Context, tenantID string) (GetTrustRow, error) {
	row := q.db.QueryRow(ctx, getTrust, tenantID)
	var i GetTrustRow
	err := row.Scan(
		&i.Issuer,
		&i.Blocked,
		&i.JwksUri,
		&i.Audiences,
		&i.ClientID,
	)
	return i, err
}

const updateTrust = `-- name: UpdateTrust :execrows
UPDATE trust
SET
    blocked = $1,
    issuer = $2,
    jwks_uri = $3,
    audiences = COALESCE($4::text[], '{}'::text[]),
    client_id = $5
WHERE
    tenant_id = $6
`

type UpdateTrustParams struct {
	Blocked   bool        `db:"blocked"`
	Issuer    string      `db:"issuer"`
	JwksUri   string      `db:"jwks_uri"`
	Audiences []string    `db:"audiences"`
	ClientID  pgtype.Text `db:"client_id"`
	TenantID  string      `db:"tenant_id"`
}

func (q *Queries) UpdateTrust(ctx context.Context, arg UpdateTrustParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateTrust,
		arg.Blocked,
		arg.Issuer,
		arg.JwksUri,
		arg.Audiences,
		arg.ClientID,
		arg.TenantID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
