//go:build go1.22

// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.1-0.20260828072548-2679cec6ca18 DO NOT EDIT.
package openapi

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"

	"github.com/oapi-codegen/runtime"
)

// ErrorModel defines model for ErrorModel.
type ErrorModel struct {
	Error            string `json:"error"`
	ErrorDescription string `json:"error_description,omitempty,omitzero"`
}

// AuthParams defines parameters for Auth.
type AuthParams struct {
	TenantID   string `form:"tenant_id" json:"tenant_id"`
	RequestURI string `form:"request_uri" json:"request_uri"`

	// ErrorURI Base URL of the UI error page. When provided and an error occurs during the
	// auth flow (including the callback), the session manager redirects to this URL
	// with an appended errorCode query parameter instead of returning a JSON error body.
	// Example: https://openkcm.com/#/tenantID/forbidden
	ErrorURI string `form:"error_uri,omitempty" json:"error_uri,omitempty,omitzero"`
}

// BclogoutFormdataBody defines parameters for Bclogout.
type BclogoutFormdataBody struct {
	// LogoutToken Logout token
	LogoutToken string `form:"logout_token" json:"logout_token"`
}

// CallbackParams defines parameters for Callback.
type CallbackParams struct {
	Code                              string `form:"code" json:"code"`
	State                             string `form:"state" json:"state"`
	UnderscoreUnderscoreHostLoginCSRF string `form:"__Host-LoginCSRF" json:"__Host-LoginCSRF"`
}

// LogoutParams defines parameters for Logout.
type LogoutParams struct {
	TenantID              string `form:"tenant_id" json:"tenant_id"`
	PostLogoutRedirectURI string `form:"post_logout_redirect_uri" json:"post_logout_redirect_uri"`
	Cookie                string `json:"Cookie"`
}

// BclogoutFormdataRequestBody defines body for Bclogout for application/x-www-form-urlencoded ContentType.
type BclogoutFormdataRequestBody BclogoutFormdataBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /sm/auth)
	Auth(w http.ResponseWriter, r *http.Request, params AuthParams)

	// (POST /sm/bclogout)
	Bclogout(w http.ResponseWriter, r *http.Request)

	// (GET /sm/callback)
	Callback(w http.ResponseWriter, r *http.Request, params CallbackParams)

	// (GET /sm/logout)
	Logout(w http.ResponseWriter, r *http.Request, params LogoutParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Auth operation middleware
func (siw *ServerInterfaceWrapper) Auth(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params AuthParams

	// ------------- Required query parameter "tenant_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "tenant_id", r.URL.Query(), &params.TenantID, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "tenant_id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tenant_id", Err: err})
		}
		return
	}

	// ------------- Required query parameter "request_uri" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "request_uri", r.URL.Query(), &params.RequestURI, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "request_uri"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "request_uri", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "error_uri" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "error_uri", r.URL.Query(), &params.ErrorURI, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "error_uri"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "error_uri", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Auth(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Bclogout operation middleware
func (siw *ServerInterfaceWrapper) Bclogout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Bclogout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Callback operation middleware
func (siw *ServerInterfaceWrapper) Callback(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CallbackParams

	// ------------- Required query parameter "code" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "code", r.URL.Query(), &params.Code, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "code"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "code", Err: err})
		}
		return
	}

	// ------------- Required query parameter "state" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "state", r.URL.Query(), &params.State, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "state"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "state", Err: err})
		}
		return
	}

	{
		var cookie *http.Cookie

		if cookie, err = r.Cookie("__Host-LoginCSRF"); err == nil {
			var value string
			err = runtime.BindStyledParameterWithOptions("simple", "__Host-LoginCSRF", cookie.Value, &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationCookie, Explode: true, Required: true, Type: "string", Format: ""})
			if err != nil {
				siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "__Host-LoginCSRF", Err: err})
				return
			}
			params.UnderscoreUnderscoreHostLoginCSRF = value

		} else {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "__Host-LoginCSRF"})
			return
		}
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Callback(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params LogoutParams

	// ------------- Required query parameter "tenant_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "tenant_id", r.URL.Query(), &params.TenantID, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "tenant_id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tenant_id", Err: err})
		}
		return
	}

	// ------------- Required query parameter "post_logout_redirect_uri" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "post_logout_redirect_uri", r.URL.Query(), &params.PostLogoutRedirectURI, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "post_logout_redirect_uri"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "post_logout_redirect_uri", Err: err})
		}
		return
	}

	headers := r.Header

	// ------------- Required header parameter "Cookie" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Cookie")]; found {
		var Cookie string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Cookie", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Cookie", valueList[0], &Cookie, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Cookie", Err: err})
			return
		}

		params.Cookie = Cookie

	} else {
		err := fmt.Errorf("Header parameter Cookie is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Cookie", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/sm/auth", wrapper.Auth)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/sm/logout", wrapper.Logout)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/sm/bclogout", wrapper.Bclogout)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/sm/callback", wrapper.Callback)

	return m
}

type AuthRequestObject struct {
	Params AuthParams
}

type AuthResponseObject interface {
	VisitAuthResponse(w http.ResponseWriter) error
}

type Auth302ResponseHeaders struct {
	Location  string
	SetCookie string
}

type Auth302Response struct {
	Headers Auth302ResponseHeaders
}

func (response Auth302Response) VisitAuthResponse(w http.ResponseWriter) error {
	{
		v, err := runtime.StyleParamWithOptions("simple", false, "Location", response.Headers.Location, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return fmt.Errorf("error styling response header Location: %w", err)
		}
		w.Header().Set("Location", v)
	}
	{
		v, err := runtime.StyleParamWithOptions("simple", false, "Set-Cookie", response.Headers.SetCookie, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return fmt.Errorf("error styling response header Set-Cookie: %w", err)
		}
		w.Header().Set("Set-Cookie", v)
	}
	w.WriteHeader(302)
	return nil
}

type AuthdefaultJSONResponse struct {
	Body       ErrorModel
	StatusCode int
}

func (response AuthdefaultJSONResponse) VisitAuthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type BclogoutRequestObject struct {
	Body *BclogoutFormdataRequestBody
}

type BclogoutResponseObject interface {
	VisitBclogoutResponse(w http.ResponseWriter) error
}

type Bclogout200ResponseHeaders struct {
	CacheControl string
}

type Bclogout200Response struct {
	Headers Bclogout200ResponseHeaders
}

func (response Bclogout200Response) VisitBclogoutResponse(w http.ResponseWriter) error {
	{
		v, err := runtime.StyleParamWithOptions("simple", false, "Cache-Control", response.Headers.CacheControl, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return fmt.Errorf("error styling response header Cache-Control: %w", err)
		}
		w.Header().Set("Cache-Control", v)
	}
	w.WriteHeader(200)
	return nil
}

type Bclogout400JSONResponse ErrorModel

func (response Bclogout400JSONResponse) VisitBclogoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CallbackRequestObject struct {
	Params CallbackParams
}

type CallbackResponseObject interface {
	VisitCallbackResponse(w http.ResponseWriter) error
}

type Callback302ResponseHeaders struct {
	Location string
}

type Callback302Response struct {
	Headers Callback302ResponseHeaders
}

func (response Callback302Response) VisitCallbackResponse(w http.ResponseWriter) error {
	{
		v, err := runtime.StyleParamWithOptions("simple", false, "Location", response.Headers.Location, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return fmt.Errorf("error styling response header Location: %w", err)
		}
		w.Header().Set("Location", v)
	}
	w.WriteHeader(302)
	return nil
}

type CallbackdefaultJSONResponse struct {
	Body       ErrorModel
	StatusCode int
}

func (response CallbackdefaultJSONResponse) VisitCallbackResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type LogoutRequestObject struct {
	Params LogoutParams
}

type LogoutResponseObject interface {
	VisitLogoutResponse(w http.ResponseWriter) error
}

type Logout302ResponseHeaders struct {
	Location string
}

type Logout302Response struct {
	Headers Logout302ResponseHeaders
}

func (response Logout302Response) VisitLogoutResponse(w http.ResponseWriter) error {
	{
		v, err := runtime.StyleParamWithOptions("simple", false, "Location", response.Headers.Location, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return fmt.Errorf("error styling response header Location: %w", err)
		}
		w.Header().Set("Location", v)
	}
	w.WriteHeader(302)
	return nil
}

type LogoutdefaultJSONResponse struct {
	Body       ErrorModel
	StatusCode int
}

func (response LogoutdefaultJSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /sm/auth)
	Auth(ctx context.Context, request AuthRequestObject) (AuthResponseObject, error)

	// (POST /sm/bclogout)
	Bclogout(ctx context.Context, request BclogoutRequestObject) (BclogoutResponseObject, error)

	// (GET /sm/callback)
	Callback(ctx context.Context, request CallbackRequestObject) (CallbackResponseObject, error)

	// (GET /sm/logout)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// Auth operation middleware
func (sh *strictHandler) Auth(w http.ResponseWriter, r *http.Request, params AuthParams) {
	var request AuthRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error) {
		return sh.ssi.Auth(ctx, request.(AuthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Auth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AuthResponseObject); ok {
		if err := validResponse.VisitAuthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Bclogout operation middleware
func (sh *strictHandler) Bclogout(w http.ResponseWriter, r *http.Request) {
	var request BclogoutRequestObject

	if err := r.ParseForm(); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode formdata: %w", err))
		return
	}
	var body BclogoutFormdataRequestBody
	if err := runtime.BindForm(&body, r.Form, nil, nil); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't bind formdata: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error) {
		return sh.ssi.Bclogout(ctx, request.(BclogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Bclogout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(BclogoutResponseObject); ok {
		if err := validResponse.VisitBclogoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Callback operation middleware
func (sh *strictHandler) Callback(w http.ResponseWriter, r *http.Request, params CallbackParams) {
	var request CallbackRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error) {
		return sh.ssi.Callback(ctx, request.(CallbackRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Callback")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CallbackResponseObject); ok {
		if err := validResponse.VisitCallbackResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Logout operation middleware
func (sh *strictHandler) Logout(w http.ResponseWriter, r *http.Request, params LogoutParams) {
	var request LogoutRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error) {
		return sh.ssi.Logout(ctx, request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		if err := validResponse.VisitLogoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
