// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Trust struct {
	TenantID   string           `db:"tenant_id"`
	Blocked    bool             `db:"blocked"`
	Issuer     string           `db:"issuer"`
	JwksUri    string           `db:"jwks_uri"`
	Audiences  []string         `db:"audiences"`
	Properties []byte           `db:"properties"`
	CreatedAt  pgtype.Timestamp `db:"created_at"`
	ClientID   pgtype.Text      `db:"client_id"`
}
