// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOIDCMapping = `-- name: CreateOIDCMapping :exec
INSERT INTO trust (
    tenant_id,
    blocked,
    issuer,
    jwks_uri,
    audiences,
    properties,
    client_id)
VALUES (
    $1,
    $2,
    $3,
    $4,
    COALESCE($5::text[], '{}'::text[]),
    $6,
    $7)
`

type CreateOIDCMappingParams struct {
	TenantID   string      `db:"tenant_id"`
	Blocked    bool        `db:"blocked"`
	Issuer     string      `db:"issuer"`
	JwksUri    string      `db:"jwks_uri"`
	Audiences  []string    `db:"audiences"`
	Properties []byte      `db:"properties"`
	ClientID   pgtype.Text `db:"client_id"`
}

func (q *Queries) CreateOIDCMapping(ctx context.Context, arg CreateOIDCMappingParams) error {
	_, err := q.db.Exec(ctx, createOIDCMapping,
		arg.TenantID,
		arg.Blocked,
		arg.Issuer,
		arg.JwksUri,
		arg.Audiences,
		arg.Properties,
		arg.ClientID,
	)
	return err
}

const deleteOIDCMapping = `-- name: DeleteOIDCMapping :execrows
DELETE FROM trust
WHERE tenant_id = $1
`

func (q *Queries) DeleteOIDCMapping(ctx context.Context, tenantID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOIDCMapping, tenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOIDCMapping = `-- name: GetOIDCMapping :one
SELECT
    issuer,
    blocked,
    jwks_uri,
    audiences,
    properties,
    client_id
FROM trust
WHERE tenant_id = $1
`

type GetOIDCMappingRow struct {
	Issuer     string      `db:"issuer"`
	Blocked    bool        `db:"blocked"`
	JwksUri    string      `db:"jwks_uri"`
	Audiences  []string    `db:"audiences"`
	Properties []byte      `db:"properties"`
	ClientID   pgtype.Text `db:"client_id"`
}

func (q *Queries) GetOIDCMapping(ctx context.Context, tenantID string) (GetOIDCMappingRow, error) {
	row := q.db.QueryRow(ctx, getOIDCMapping, tenantID)
	var i GetOIDCMappingRow
	err := row.Scan(
		&i.Issuer,
		&i.Blocked,
		&i.JwksUri,
		&i.Audiences,
		&i.Properties,
		&i.ClientID,
	)
	return i, err
}

const updateOIDCMapping = `-- name: UpdateOIDCMapping :execrows
UPDATE trust
SET
    blocked = $1,
    issuer = $2,
    jwks_uri = $3,
    audiences = COALESCE($4::text[], '{}'::text[]),
    properties = $5,
    client_id = $6
WHERE
    tenant_id = $7
`

type UpdateOIDCMappingParams struct {
	Blocked    bool        `db:"blocked"`
	Issuer     string      `db:"issuer"`
	JwksUri    string      `db:"jwks_uri"`
	Audiences  []string    `db:"audiences"`
	Properties []byte      `db:"properties"`
	ClientID   pgtype.Text `db:"client_id"`
	TenantID   string      `db:"tenant_id"`
}

func (q *Queries) UpdateOIDCMapping(ctx context.Context, arg UpdateOIDCMappingParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateOIDCMapping,
		arg.Blocked,
		arg.Issuer,
		arg.JwksUri,
		arg.Audiences,
		arg.Properties,
		arg.ClientID,
		arg.TenantID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
