apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "session-manager.name" . }}-migrate-config
  labels:
    {{- include "session-manager.labels" . | nindent 4 }}
    app.kubernetes.io/component: migrate
immutable: {{ .Values.config.isImmutable | default false }}
data:
 config.yaml: |-
   # Based on github.com/openkcm/common-sdk/pkg/commoncfg
   application:
      name: {{ .Chart.Name }}
    {{- with .Values.config }}
      environment: {{ .environment }}
      {{- with .labels }}
      labels:
        {{- toYaml . | nindent 8 }}
      {{- end}}

    logger:
      {{- toYaml .logger | nindent 6 }}

    # Based on github.com/openkcm/session-manager/pkg/config
    database:
      {{- toYaml .database | nindent 6 }}
    migrate:
      {{- toYaml .migrate | nindent 6 }}
    {{- end }}
