apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "session-manager.fullname" . }}
  namespace: {{ include "session-manager.namespace" . }}
  labels:
    {{- include "session-manager.labels" . | nindent 4 }}
spec:
  {{- if .Values.hpa.enabled }}
  replicas: {{ .Values.hpa.minReplicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "session-manager.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.pod.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "session-manager.labels" . | nindent 8 }}
        {{- with .Values.pod.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "session-manager.serviceAccountName" . }}
      {{- with .Values.pod.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        {{- with .Values.extraContainers }}
          {{- toYaml . | nindent 10 }}
        {{- end }}
        - name: {{ include "session-manager.name" . }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ template "session-manager.image" (tuple .Values.image $.Chart.AppVersion) }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.image.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            {{- with .Values.extraPorts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: K8S_NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            {{- with .Values.extraEnvs }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.extraEnvsFrom }}
          envFrom:
          {{- . | toYaml | nindent 12 }}
          {{- end }}
          livenessProbe:
          {{- with .Values.livenessProbe }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: {{ include "session-manager.name" . }}-config-volume
              mountPath: /etc/session-manager
              readOnly: true
          {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: {{ include "session-manager.name" . }}-config-volume
          configMap:
            name: {{ include "session-manager.name" . }}-config
      {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pod.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pod.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pod.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.pod.tolerations }}
      tolerations:
        {{- toYaml . | nindent 6 }}
      {{- end }}
