{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "session-manager.serviceAccountName" . }}-api-pub
  labels:
    {{- include "session-manager.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-pub
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
