apiVersion: v1
kind: Service
metadata:
  name: {{ include "session-manager.fullname" . }}-api-pub
  labels:
    {{- include "session-manager.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: api-pub
{{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
{{- with .Values.service.ports }}
  ports:
    {{- toYaml . | nindent 4 }}
{{- end }}
  selector:
    {{- include "session-manager.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api-pub
